( echo " /usr/sbin/lapenv" >> /etc/rc.d/rc.S )
( ln /etc/rc.d/rc.lapenv /usr/sbin/lapenv -s )
( cd usr/sbin ; rm -rf lapenv )
( cd usr/sbin ; ln -sf /etc/rc.d/rc.lapenv lapenv )
( cd usr/sbin ; rm -rf lapenv )
( cd usr/sbin ; ln -sf /etc/rc.d/rc.lapenv lapenv )
( cd usr/sbin ; rm -rf lapenv )
( cd usr/sbin ; ln -sf /etc/rc.d/rc.lapenv lapenv )
( cd usr/sbin ; rm -rf lapenv )
( cd usr/sbin ; ln -sf /etc/rc.d/rc.lapenv lapenv )
( cd usr/sbin ; rm -rf lapenv )
( cd usr/sbin ; ln -sf /etc/rc.d/rc.lapenv lapenv )
